language: r
cache: packages

before_install:
- "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng texlive-lang-german"
- tlmgr install index

install:
  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH

script:
- mkdir _build
- pdflatex -output-directory _build vorlage.tex

deploy:
  provider: releases
  api_key:
    - secure: 
  file: vorlage.pdf
  skip_cleanup: true
  on:
    all_branches: true